package com.example.last.entity;

import javax.persistence.*;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.NumberFormat;

import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZonedDateTime;

@Entity 
@Data   
@NoArgsConstructor
public class Employee{

    @Id 
    @GeneratedValue(strategy = GenerationType.AUTO) 
    private Long id; 
    
    @Column(nullable = false)
    private String name;

    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
    private LocalDate birthdate;

    private LocalTime entry;

    private ZonedDateTime lastLogin; 
    
    private Boolean isAdmin; 

    @NumberFormat
    private Double timeLogged;

    @ManyToOne
    @JoinColumn( foreignKey = @ForeignKey(name = "FK_POSITION"), name = "position")
    private Position position;
    
    //projection and hateoas generated by data rest fail with fetch = FetchType.LAZY
    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(foreignKey = @ForeignKey(name = "FK_ADDRESS"), name = "address")
    private Address address;
    
}